/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Answer */
        post: operations["generate_answer_chat_prompt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat History */
        get: operations["get_chat_history_chat_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/review-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Chat Action */
        post: operations["review_chat_action_chat_review_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Logs */
        get: operations["audit_logs_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/examples/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_examples_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/examples/by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Examples */
        get: operations["examples_examples_by_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/examples/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Examples Api */
        post: operations["search_examples_api_examples_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Feedback */
        post: operations["create_feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Feedback */
        get: operations["recent_feedback_feedback_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/export-eval-case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Eval Case */
        post: operations["export_eval_case_feedback_export_eval_case_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Info */
        get: operations["model_info_model_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge Items */
        get: operations["knowledge_items_knowledge_items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_knowledge_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Item */
        put: operations["update_item_knowledge_items__item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/items/{item_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Item */
        post: operations["archive_item_knowledge_items__item_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/items/{item_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Item */
        post: operations["review_item_knowledge_items__item_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/export-approved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Approved */
        get: operations["export_approved_knowledge_export_approved_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/publish-approved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Approved */
        post: operations["publish_approved_knowledge_publish_approved_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/publish-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Publish History */
        get: operations["publish_history_knowledge_publish_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/rollback-latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback Latest */
        post: operations["rollback_latest_knowledge_rollback_latest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops Metrics */
        get: operations["ops_metrics_ops_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Order State */
        get: operations["read_order_state_orders__order_id__state_get"];
        /** Save Order State */
        put: operations["save_order_state_orders__order_id__state_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompt/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prompt Versions */
        get: operations["prompt_versions_prompt_versions_get"];
        put?: never;
        /** Create Version */
        post: operations["create_version_prompt_versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompt/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Prompt */
        get: operations["active_prompt_prompt_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompt/versions/{version_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Status */
        post: operations["update_status_prompt_versions__version_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompt/versions/{version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Version */
        post: operations["activate_version_prompt_versions__version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompt/rollback-latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback Latest */
        post: operations["rollback_latest_prompt_rollback_latest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release Checklist */
        get: operations["release_checklist_release_checklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieval/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Retrieval Config */
        get: operations["get_retrieval_config_retrieval_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieval/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Retrieval */
        post: operations["search_retrieval_retrieval_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieval/prompt-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Prompt */
        post: operations["preview_prompt_retrieval_prompt_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditLogItem */
        AuditLogItem: {
            /** Id */
            id: number;
            /** Operator Id */
            operator_id: string;
            /** Operator Role */
            operator_role: string;
            /** Action Type */
            action_type: string;
            /** Object Type */
            object_type: string;
            /** Object Id */
            object_id: string;
            /**
             * Request Id
             * @default
             */
            request_id: string;
            /**
             * Before Summary
             * @default
             */
            before_summary: string;
            /**
             * After Summary
             * @default
             */
            after_summary: string;
            /**
             * Ip
             * @default
             */
            ip: string;
            /**
             * Device Info
             * @default
             */
            device_info: string;
            /** Created At */
            created_at: string;
        };
        /** AuditLogListResponse */
        AuditLogListResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["AuditLogItem"][];
        };
        /** CategoriesResponse */
        CategoriesResponse: {
            /** Categories */
            categories: string[];
            /** Count */
            count: number;
        };
        /** ChatHistoryMessage */
        ChatHistoryMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Intent */
            intent?: {
                [key: string]: unknown;
            };
            /**
             * Risk Level
             * @default low
             */
            risk_level: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
        };
        /** ChatHistoryResponse */
        ChatHistoryResponse: {
            /**
             * User Id
             * @default demo_user
             */
            user_id: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /** Order Id */
            order_id?: string | null;
            /** Messages */
            messages?: components["schemas"]["ChatHistoryMessage"][];
            /** Latest Response */
            latest_response?: {
                [key: string]: unknown;
            };
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * User Id
             * @default demo_user
             */
            user_id: string;
            /** Session Id */
            session_id?: string | null;
            /** Order Id */
            order_id?: string | null;
            /**
             * Channel
             * @default test
             */
            channel: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /**
             * Request Id
             * @default
             */
            request_id: string;
            /** Reply */
            reply: string;
            /**
             * Risk Level
             * @default low
             */
            risk_level: string;
            /**
             * Confidence Level
             * @default medium
             */
            confidence_level: string;
            /**
             * Need Human Review
             * @default true
             */
            need_human_review: boolean;
            /**
             * Human Review Reason
             * @default v1 默认客服确认后发送
             */
            human_review_reason: string;
            /** Citations */
            citations?: {
                [key: string]: unknown;
            }[];
            /**
             * Conversation Status
             * @default pending_agent_review
             */
            conversation_status: string;
            /**
             * Answer Basis
             * @default
             */
            answer_basis: string;
            /**
             * Answer Strategy
             * @default model_reply
             * @enum {string}
             */
            answer_strategy: "model_reply" | "composer_repair" | "safety_fallback";
            /** Evidence Citations */
            evidence_citations?: {
                [key: string]: unknown;
            }[];
            /** Tool Results */
            tool_results?: {
                [key: string]: unknown;
            }[];
            /** Memory Snapshot */
            memory_snapshot?: {
                [key: string]: unknown;
            };
            /** Decision Trace */
            decision_trace?: {
                [key: string]: unknown;
            };
            /** Full Trace */
            full_trace?: {
                [key: string]: unknown;
            }[];
            /** Handoff Ticket */
            handoff_ticket?: {
                [key: string]: unknown;
            } | null;
            /** Token Usage */
            token_usage?: {
                [key: string]: unknown;
            };
            /** Confidence Score */
            confidence_score: number;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * User Id
             * @default demo_user
             */
            user_id: string;
            /** Order Id */
            order_id?: string | null;
            /** Intent Analysis */
            intent_analysis?: {
                [key: string]: unknown;
            };
            /** Context Used */
            context_used?: {
                [key: string]: unknown;
            };
            /** Safety Status */
            safety_status?: {
                [key: string]: unknown;
            };
            /** Final Prompt */
            final_prompt: string;
            /**
             * Prompt Version
             * @default
             */
            prompt_version: string;
            /** Retrieved Documents */
            retrieved_documents: string[];
            /** Retrieved Items */
            retrieved_items?: {
                [key: string]: unknown;
            }[];
            /** Prompt Context Items */
            prompt_context_items?: components["schemas"]["PromptContextItemResponse"][];
            trace: components["schemas"]["ChatTrace"];
            /**
             * Expected Intent
             * @default
             */
            expected_intent: string;
            /** Expected Evidence Keywords */
            expected_evidence_keywords?: string[];
            /** Matched Evidence Keywords */
            matched_evidence_keywords?: string[];
            /** Missing Evidence Keywords */
            missing_evidence_keywords?: string[];
            /** Forbidden Keywords */
            forbidden_keywords?: string[];
            /** Forbidden Keyword Hits */
            forbidden_keyword_hits?: string[];
            /**
             * Used Primary Evidence
             * @default false
             */
            used_primary_evidence: boolean;
            /**
             * Mixed Supporting Intent
             * @default false
             */
            mixed_supporting_intent: boolean;
            /** Risky Promises */
            risky_promises?: string[];
            /**
             * Needs Manual Review
             * @default false
             */
            needs_manual_review: boolean;
            /** Manual Judgment */
            manual_judgment?: {
                [key: string]: unknown;
            };
            /**
             * Issue Type
             * @default
             */
            issue_type: string;
            /**
             * Suggested Layer
             * @default
             */
            suggested_layer: string;
            /** Evaluation Metrics */
            evaluation_metrics?: {
                [key: string]: unknown;
            };
        };
        /** ChatReviewActionRequest */
        ChatReviewActionRequest: {
            /** Request Id */
            request_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "accepted" | "edited_and_sent" | "human_handoff" | "marked_bad_case";
            /**
             * Operator Id
             * @default demo_agent
             */
            operator_id: string;
            /**
             * Operator Role
             * @default agent
             */
            operator_role: string;
            /**
             * Final Reply
             * @default
             */
            final_reply: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** ChatReviewActionResponse */
        ChatReviewActionResponse: {
            /** Request Id */
            request_id: string;
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: string;
            /** Order Id */
            order_id?: string | null;
            /**
             * Action
             * @enum {string}
             */
            action: "accepted" | "edited_and_sent" | "human_handoff" | "marked_bad_case";
            /** Status */
            status: string;
            /**
             * Final Reply
             * @default
             */
            final_reply: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Handoff Ticket */
            handoff_ticket?: {
                [key: string]: unknown;
            } | null;
            /** Audit Id */
            audit_id?: number | null;
            /**
             * Saved
             * @default true
             */
            saved: boolean;
            /** Created At */
            created_at: string;
        };
        /** ChatTrace */
        ChatTrace: {
            /** Retrieval Count */
            retrieval_count: number;
            /**
             * Request Id
             * @default
             */
            request_id: string;
            /**
             * User Id
             * @default
             */
            user_id: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /** Order Id */
            order_id?: string | null;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Top1 Intent
             * @default
             */
            top1_intent: string;
            /** Used Fallback Prompt */
            used_fallback_prompt: boolean;
            /** Reply Rules Applied */
            reply_rules_applied: boolean;
            /**
             * Answer Source
             * @description rag or fallback
             */
            answer_source: string;
            /** Degraded */
            degraded: boolean;
            /**
             * Failure Stage
             * @description none, retrieval, generation, or reply_rules
             */
            failure_stage: string;
            /** Fallback Reason */
            fallback_reason: string;
        };
        /** ExampleItem */
        ExampleItem: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** ExamplesByCategoryResponse */
        ExamplesByCategoryResponse: {
            /** Category */
            category: string;
            /** Count */
            count: number;
            /** Examples */
            examples: components["schemas"]["ExampleItem"][];
        };
        /** ExportEvalCaseRequest */
        ExportEvalCaseRequest: {
            /** Feedback Id */
            feedback_id: number;
        };
        /** ExportEvalCaseResponse */
        ExportEvalCaseResponse: {
            /** Feedback Id */
            feedback_id: number;
            /** Eval Case */
            eval_case: {
                [key: string]: unknown;
            };
        };
        /** FeedbackItem */
        FeedbackItem: {
            /** Id */
            id: number;
            /** Request Id */
            request_id: string;
            /** Query */
            query: string;
            /** Reply */
            reply: string;
            /** Helpful */
            helpful: boolean;
            /** Reason */
            reason: string;
            /** Expected Reply */
            expected_reply: string;
            /** Top1 Intent */
            top1_intent: string;
            /** Latency Ms */
            latency_ms: number;
            /** Answer Source */
            answer_source: string;
            /** Failure Stage */
            failure_stage: string;
            /** Exported */
            exported: boolean;
            /** Created At */
            created_at: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Request Id */
            request_id: string;
            /** Query */
            query: string;
            /** Reply */
            reply: string;
            /** Helpful */
            helpful: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Expected Reply
             * @default
             */
            expected_reply: string;
            /** Trace */
            trace?: {
                [key: string]: unknown;
            };
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Feedback Id */
            feedback_id: number;
            /** Saved */
            saved: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KnowledgeExportResponse */
        KnowledgeExportResponse: {
            /** Count */
            count: number;
            /** Jsonl */
            jsonl: string;
        };
        /** KnowledgeItem */
        KnowledgeItem: {
            /** Id */
            id: number;
            /** Base Id */
            base_id: string;
            /** Version */
            version: number;
            /** Title */
            title: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Category */
            category: string;
            /** Intent */
            intent: string;
            /** Status */
            status: string;
            /** Owner */
            owner: string;
            /** Source */
            source: string;
            /** Effective At */
            effective_at: string;
            /** Expired At */
            expired_at: string;
            /** Review Note */
            review_note: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Reviewed At */
            reviewed_at: string;
        };
        /** KnowledgeItemPayload */
        KnowledgeItemPayload: {
            /**
             * Title
             * @default
             */
            title: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Category */
            category: string;
            /** Intent */
            intent: string;
            /**
             * Owner
             * @default knowledge_ops
             */
            owner: string;
            /**
             * Source
             * @default knowledge_ops
             */
            source: string;
            /**
             * Effective At
             * @default
             */
            effective_at: string;
            /**
             * Expired At
             * @default
             */
            expired_at: string;
        };
        /** KnowledgeListResponse */
        KnowledgeListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["KnowledgeItem"][];
        };
        /** KnowledgePublishHistoryItem */
        KnowledgePublishHistoryItem: {
            /** Id */
            id: number;
            /** Publish Id */
            publish_id: string;
            /** Action */
            action: string;
            /** Status */
            status: string;
            /** Merged Count */
            merged_count: number;
            /** Item Ids */
            item_ids: number[];
            /** Backup Path */
            backup_path: string;
            /** Knowledge Path */
            knowledge_path: string;
            /** Faiss Index Path */
            faiss_index_path: string;
            /** Note */
            note: string;
            /** Created At */
            created_at: string;
        };
        /** KnowledgePublishHistoryResponse */
        KnowledgePublishHistoryResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["KnowledgePublishHistoryItem"][];
        };
        /** KnowledgePublishResponse */
        KnowledgePublishResponse: {
            /** Id */
            id: number;
            /** Publish Id */
            publish_id: string;
            /** Action */
            action: string;
            /** Status */
            status: string;
            /** Merged Count */
            merged_count: number;
            /** Item Ids */
            item_ids: number[];
            /** Backup Path */
            backup_path: string;
            /** Knowledge Path */
            knowledge_path: string;
            /** Faiss Index Path */
            faiss_index_path: string;
            /** Note */
            note: string;
            /** Created At */
            created_at: string;
        };
        /** KnowledgeReviewRequest */
        KnowledgeReviewRequest: {
            /** Status */
            status: string;
            /**
             * Review Note
             * @default
             */
            review_note: string;
        };
        /** ModelInfoResponse */
        ModelInfoResponse: {
            /**
             * Generation Provider
             * @default
             */
            generation_provider: string;
            /**
             * Online Model Name
             * @default
             */
            online_model_name: string;
            /**
             * Online Api Base Url Configured
             * @default false
             */
            online_api_base_url_configured: boolean;
            /**
             * Online Api Key Env
             * @default
             */
            online_api_key_env: string;
            /** Base Model */
            base_model: string;
            /** Adapter Enabled */
            adapter_enabled: boolean;
            /** Adapter Name */
            adapter_name: string | null;
        };
        /** OpsMetricsResponse */
        OpsMetricsResponse: {
            /**
             * Source
             * @default
             */
            source: string;
            /** Request Count */
            request_count: number;
            /** Failure Count */
            failure_count: number;
            /** Average Latency Ms */
            average_latency_ms: number;
            /** P95 Latency Ms */
            p95_latency_ms: number;
            /** Empty Retrieval Count */
            empty_retrieval_count: number;
            /** Reply Rules Hit Count */
            reply_rules_hit_count: number;
            /** Fallback Count */
            fallback_count: number;
            /** Accepted Count */
            accepted_count: number;
            /** Edited Sent Count */
            edited_sent_count: number;
            /** Human Handoff Count */
            human_handoff_count: number;
            /** Bad Case Count */
            bad_case_count: number;
            /** Reviewed Count */
            reviewed_count: number;
            /** Accepted Rate */
            accepted_rate: number;
            /** Edited Sent Rate */
            edited_sent_rate: number;
            /** Human Handoff Rate */
            human_handoff_rate: number;
            /** Bad Case Rate */
            bad_case_rate: number;
            /** Token Recorded Count */
            token_recorded_count: number;
            /** Token Record Rate */
            token_record_rate: number;
            /** Total Prompt Tokens */
            total_prompt_tokens: number;
            /** Total Completion Tokens */
            total_completion_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            /** Average Tokens Per Request */
            average_tokens_per_request: number;
        };
        /** OrderStateRequest */
        OrderStateRequest: {
            /**
             * User Id
             * @default demo_user
             */
            user_id: string;
            /** Order Id */
            order_id: string;
            /** Status */
            status: string;
            /**
             * Status Label
             * @default
             */
            status_label: string;
            /**
             * Delivery Status
             * @default
             */
            delivery_status: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Refund Status
             * @default none
             */
            refund_status: string;
            /**
             * Store Name
             * @default
             */
            store_name: string;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** OrderStateResponse */
        OrderStateResponse: {
            /**
             * User Id
             * @default demo_user
             */
            user_id: string;
            /** Order Id */
            order_id: string;
            /** Status */
            status: string;
            /**
             * Status Label
             * @default
             */
            status_label: string;
            /**
             * Delivery Status
             * @default
             */
            delivery_status: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Refund Status
             * @default none
             */
            refund_status: string;
            /**
             * Store Name
             * @default
             */
            store_name: string;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /** PromptContextItemResponse */
        PromptContextItemResponse: {
            /** Role */
            role: string;
            /** Evidence Strength */
            evidence_strength: string;
            /**
             * Display Title
             * @default
             */
            display_title: string;
            /**
             * Evidence Summary
             * @default
             */
            evidence_summary: string;
            /**
             * Prompt Instruction
             * @default
             */
            prompt_instruction: string;
            /**
             * Source Question
             * @default
             */
            source_question: string;
            /**
             * Source Answer
             * @default
             */
            source_answer: string;
            /** Rank */
            rank: number;
            /**
             * Knowledge Id
             * @default
             */
            knowledge_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Version
             * @default
             */
            version: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
            /**
             * Source
             * @default
             */
            source: string;
            /** Category */
            category: string;
            /** Intent */
            intent: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Score */
            score: number;
            /** Rerank Score */
            rerank_score: number;
        };
        /** PromptPreviewResponse */
        PromptPreviewResponse: {
            /** Query */
            query: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "dense" | "hybrid";
            /** Count */
            count: number;
            /** Prompt */
            prompt: string;
            /** Prompt Context Items */
            prompt_context_items: components["schemas"]["RetrievalResultItem"][];
            /** Results */
            results: components["schemas"]["RetrievalResultItem"][];
        };
        /** PromptVersionItem */
        PromptVersionItem: {
            /** Id */
            id: number;
            /** Version */
            version: string;
            /** Status */
            status: string;
            /** System Prompt */
            system_prompt: string;
            /** Developer Prompt */
            developer_prompt: string;
            /** Change Reason */
            change_reason: string;
            /** Author */
            author: string;
            /** Evaluation Result */
            evaluation_result: string;
            /** Effective At */
            effective_at: string;
            /** Created At */
            created_at: string;
            /** Activated At */
            activated_at: string;
            /** Rolled Back From */
            rolled_back_from: string;
        };
        /** PromptVersionListResponse */
        PromptVersionListResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["PromptVersionItem"][];
        };
        /** PromptVersionPayload */
        PromptVersionPayload: {
            /**
             * Version
             * @default
             */
            version: string;
            /** System Prompt */
            system_prompt: string;
            /**
             * Developer Prompt
             * @default
             */
            developer_prompt: string;
            /**
             * Change Reason
             * @default
             */
            change_reason: string;
            /**
             * Evaluation Result
             * @default
             */
            evaluation_result: string;
            /**
             * Effective At
             * @default
             */
            effective_at: string;
        };
        /** PromptVersionStatusRequest */
        PromptVersionStatusRequest: {
            /** Status */
            status: string;
            /**
             * Evaluation Result
             * @default
             */
            evaluation_result: string;
        };
        /** RagConfigResponse */
        RagConfigResponse: {
            /** Embedding Model Name */
            embedding_model_name: string;
            /** Reranker Model Name */
            reranker_model_name: string;
            /** Model Rerank Weight */
            model_rerank_weight: number;
            /** Min Vector Score */
            min_vector_score: number;
            /** Faiss Store Dir */
            faiss_store_dir: string;
            /** Faiss Index Path */
            faiss_index_path: string;
            /** Faiss Docs Path */
            faiss_docs_path: string;
            /** Reply Rules Enabled */
            reply_rules_enabled: boolean;
            /**
             * Vector Preprocessing Version
             * @default
             */
            vector_preprocessing_version: string;
            /**
             * Vector Document Count
             * @default 0
             */
            vector_document_count: number;
            /**
             * Vector Dimension
             * @default 0
             */
            vector_dimension: number;
            /**
             * Vector Built At
             * @default
             */
            vector_built_at: string;
            /**
             * Vector Manifest Status
             * @default missing
             */
            vector_manifest_status: string;
        };
        /** RecentFeedbackResponse */
        RecentFeedbackResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["FeedbackItem"][];
        };
        /** ReleaseChecklistItem */
        ReleaseChecklistItem: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Evidence */
            evidence: string;
            /**
             * Next Step
             * @default
             */
            next_step: string;
        };
        /** ReleaseChecklistResponse */
        ReleaseChecklistResponse: {
            /** Ready */
            ready: boolean;
            /** Failed Count */
            failed_count: number;
            /** Warning Count */
            warning_count: number;
            /** Items */
            items: components["schemas"]["ReleaseChecklistItem"][];
        };
        /** RetrievalResultItem */
        RetrievalResultItem: {
            /**
             * Role
             * @default
             */
            role: string;
            /**
             * Evidence Strength
             * @default normal
             */
            evidence_strength: string;
            /**
             * Display Title
             * @default
             */
            display_title: string;
            /**
             * Evidence Summary
             * @default
             */
            evidence_summary: string;
            /**
             * Prompt Instruction
             * @default
             */
            prompt_instruction: string;
            /**
             * Source Question
             * @default
             */
            source_question: string;
            /**
             * Source Answer
             * @default
             */
            source_answer: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** Rerank Score */
            rerank_score: number;
            /** Model Rerank Score */
            model_rerank_score: number;
            /** Vector Score */
            vector_score: number;
            /** Keyword Bonus */
            keyword_bonus: number;
            /** Direction Penalty */
            direction_penalty: number;
            /** Dense Rank */
            dense_rank?: number | null;
            /** Lexical Rank */
            lexical_rank?: number | null;
            /**
             * Dense Score
             * @default 0
             */
            dense_score: number;
            /**
             * Lexical Score
             * @default 0
             */
            lexical_score: number;
            /**
             * Rrf Score
             * @default 0
             */
            rrf_score: number;
            /**
             * Retrieval Origin
             * @default dense
             */
            retrieval_origin: string;
            /**
             * Reranker Degraded
             * @default false
             */
            reranker_degraded: boolean;
            /**
             * Reranker Error
             * @default
             */
            reranker_error: string;
            /** Category */
            category: string;
            /** Intent */
            intent: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** RetrievalSearchRequest */
        RetrievalSearchRequest: {
            /** Query */
            query: string;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "dense" | "hybrid";
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /**
             * Min Score
             * @default 0.4
             */
            min_score: number;
        };
        /** RetrievalSearchResponse */
        RetrievalSearchResponse: {
            /** Query */
            query: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "dense" | "hybrid";
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["RetrievalResultItem"][];
        };
        /** SearchExamplesRequest */
        SearchExamplesRequest: {
            /** Keyword */
            keyword: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /** SearchExamplesResponse */
        SearchExamplesResponse: {
            /** Keyword */
            keyword: string;
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
        };
        /** SearchResultItem */
        SearchResultItem: {
            /** Category */
            category: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_answer_chat_prompt_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_history_chat_history_get: {
        parameters: {
            query?: {
                user_id?: string;
                order_id?: string | null;
                session_id?: string | null;
                limit?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_chat_action_chat_review_action_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatReviewActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatReviewActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_logs_audit_logs_get: {
        parameters: {
            query?: {
                limit?: number;
                action_type?: string;
                object_type?: string;
                operator_role?: string;
                request_id?: string;
            };
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_examples_categories_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    examples_examples_by_category_get: {
        parameters: {
            query: {
                category: string;
                limit?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamplesByCategoryResponse"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Category not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_examples_api_examples_search_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchExamplesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchExamplesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_feedback_feedback_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                helpful?: boolean | null;
                intent?: string;
                failure_stage?: string;
            };
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_eval_case_feedback_export_eval_case_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportEvalCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportEvalCaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_info_model_info_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_items_knowledge_items_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: string;
                intent?: string;
                status?: string;
                keyword?: string;
            };
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_knowledge_items_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeItemPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_knowledge_items__item_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeItemPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_item_knowledge_items__item_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_item_knowledge_items__item_id__review_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_approved_knowledge_export_approved_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_approved_knowledge_publish_approved_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_history_knowledge_publish_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePublishHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_latest_knowledge_rollback_latest_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_metrics_ops_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_order_state_orders__order_id__state_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_order_state_orders__order_id__state_put: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prompt_versions_prompt_versions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_prompt_versions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptVersionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_prompt_prompt_active_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_prompt_versions__version_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptVersionStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_version_prompt_versions__version_id__activate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_latest_prompt_rollback_latest_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_checklist_release_checklist_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseChecklistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_retrieval_config_retrieval_config_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_retrieval_retrieval_search_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_prompt_retrieval_prompt_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
                "X-Operator-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
